Add array first last rule
renuo/renuocop pull request #16
Opened 2024-09-05 11:46 UTC by CuddlyBunion341

https://docs.rubocop.org/rubocop/cops_style.html#stylearrayfirstlast

```
# bad
arr[0]
arr[-1]

# good
arr.first
arr.last
arr[0] = 2
arr[0][-2]
```

I don't see a situation where we would prefer `arr[0]` or `arr[-1]` over `arr.first` and `arr.last`. Also `first` and `last` are more human readable.

2024-09-05 13:27 UTC, coorasse reviewed
I don't have a strong opinion on that. I am fine with both

2024-09-06 06:37 UTC, simon-isler reviewed
same as @coorasse. I'd personally not restrict it

2024-09-06 10:15 UTC, rnestler requested changes
I'm against enforcing it, since depending on the situation one or the other may make more sense. I'd hate to see something like
```ruby
foo.first = 'bar'
foo[1] = 'baz'
```
Of course you could use `foo.second` in that case, but I think that
```ruby
foo[0] = 'bar'
foo[1] = 'baz'
````
Is more readable because of the alignment.

2024-09-06 10:24 UTC, firemind requested changes
I'm also against adding this as enforcing consistency will lead to weirdness in edge-cases.

2024-09-06 11:26 UTC, CuddlyBunion341 commented
Thanks for your feedback. Seeing how unhappy you are with the proposal, I will close this PR.

2024-09-06 11:26 UTC, closed without merging